# Generated by Django 4.1.5 on 2023-03-24 16:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="affiliatedveterinary",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="affiliatedveterinary",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="affiliatedveterinary",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="service",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="service",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="service",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="veterinarypromotion",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="veterinarypromotion",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="veterinarypromotion",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="veterinaryservice",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="veterinaryservice",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
