# Generated by Django 4.1.5 on 2023-03-24 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_affiliatedveterinary_active_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Owner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("document_id", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("lastname", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=255, null=True)),
                ("birthdate", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Owner",
                "verbose_name_plural": "Owners",
                "ordering": ["name", "lastname"],
            },
        ),
        migrations.AlterModelOptions(
            name="affiliatedveterinary",
            options={
                "ordering": ("name",),
                "verbose_name": "Affiliated Veterinary",
                "verbose_name_plural": "Affiliated Veterinaries",
            },
        ),
        migrations.AlterModelOptions(
            name="service",
            options={
                "ordering": ("name",),
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
            },
        ),
        migrations.AlterModelOptions(
            name="subscriptionplan",
            options={
                "ordering": ("name",),
                "verbose_name": "Subscription Plan",
                "verbose_name_plural": "Subscription Plans",
            },
        ),
        migrations.AlterModelOptions(
            name="veterinarypromotion",
            options={
                "ordering": ("veterinary",),
                "verbose_name": "Veterinary Promotion",
                "verbose_name_plural": "Veterinary Promotions",
            },
        ),
        migrations.AlterModelOptions(
            name="veterinaryservice",
            options={
                "ordering": ("veterinary",),
                "verbose_name": "Veterinary Service",
                "verbose_name_plural": "Veterinary Services",
            },
        ),
        migrations.RemoveField(model_name="affiliatedveterinary", name="address",),
        migrations.RemoveField(model_name="affiliatedveterinary", name="email",),
        migrations.RemoveField(model_name="affiliatedveterinary", name="phone",),
        migrations.AddField(
            model_name="affiliatedveterinary",
            name="facebook",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="affiliatedveterinary",
            name="instagram",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="affiliatedveterinary",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="pet/AffiliatedVeterinary/"
            ),
        ),
        migrations.AddField(
            model_name="affiliatedveterinary",
            name="mission",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="affiliatedveterinary",
            name="tiktok",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="affiliatedveterinary",
            name="twitter",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="affiliatedveterinary",
            name="vision",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="affiliatedveterinary",
            name="web_page",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="affiliatedveterinary",
            name="owner",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="core.owner"
            ),
        ),
    ]
