# Generated by Django 4.1.5 on 2023-03-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_owner_alter_affiliatedveterinary_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="owner",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="core/Owner/"),
        ),
        migrations.AlterField(
            model_name="affiliatedveterinary",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="core/AffiliatedVeterinary/"
            ),
        ),
    ]
